name: Trigger Website Update

on:
  push:
    branches:
      - main
    paths:
      - '**/*.pdf'
      - '**/*.tex'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website update
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.WEBSITE_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/varohlen/arohlense/dispatches \
            -d '{"event_type": "exam-update"}'
